### ISSUE TITLE
Implement a Mixxx controller for the jog-display

### ISSUE THREAD

**Issue by jclaveau** [jclaveau/cdj-retrofit#11]
### Todo
- [ ] HID vs Midi? https://github.com/mixxxdj/mixxx/wiki/hid%20mapping
    - [ ] How to display bass and hi-hats on the jog screen?
        - Controller screen support (wip / hid): https://github.com/mixxxdj/mixxx/pull/11407
    - => `Use HID` as the existing CDJ 900 controller. Also HID works well with Teensy with the "Raw HID" usb type.
        - https://github.com/mixxxdj/mixxx/blob/main/res/controllers/Pioneer-CDJ-HID.js
- [ ] Jog component?
- [ ] Places cues
- [ ] Add kiks to the blue pixels
- [ ] Add hi-hats to the red pixels
- [ ] Investigate effects display?
- [ ] Mapping

### Resources
- Contributing to mappings https://github.com/mixxxdj/mixxx/wiki/Contributing-Mappings
- Midi components: https://github.com/mixxxdj/mixxx/wiki/Components-JS
- New controller system https://github.com/mixxxdj/mixxx/wiki/New-controller-system
