### ISSUE TITLE
Be able to control the screen from Arduino

### ISSUE THREAD

**Issue by jclaveau** [jclaveau/cdj-retrofit#4]
### Goals
- https://github.com/jclaveau/cdj-retrofit/issues/3

### Todo
- [x] Reverse-engeneering
    - [x] Required power
        => 12v + 5v from arduino
    - [x] Identify pins 
        => blink / latency / signal / clock
    - [x] Identify the protocol
        - Try with uint8_t instead of ints
        - Try with buffered Spi.transfer()
    - [x] Find the tunings
    - [x] Digital analysis
         - PulseView session: https://github.com/jclaveau/cdj-retrofit/blob/9cee77365f1d7b6a46307324cb65ad81c9e356b2/reverse-engineering/DWX3024%20JFLB%20-%20jog%20screen%20(+%20JOGB%20DWX3026%20ASSY)/jog-dispay.paused.lht00su1.sr
- [x] Implement an Arduino sketch driver
    - https://github.com/jclaveau/cdj-retrofit/blob/9cee77365f1d7b6a46307324cb65ad81c9e356b2/reverse-engineering/DWX3024%20JFLB%20-%20jog%20screen%20(+%20JOGB%20DWX3026%20ASSY)/jog-display/jog-display.ino 
    - [x] Commands to control it
    - [x] Non blocking operations
    - [x] Shades of grey
    - [x] Animations
        - [x] Non blocking frame update 
- [ ] Fine tune the blink sequence
    - [x] Blink after serial transfer
    - [x] Command for blink duration
    - [x] Display mid pixels only during mid blink
        - [x] Remove sides support for vinyl pixel? 
    - [x] More shades of grey
- [ ] Set multiple values in range command

### Later
- [ ] Compensate the strength of the mid pixels (due to the latency?)
- [ ] Prod / Debug mode with shades of grey depending on it
- [ ] Use USBTinyISP instead of a loaded programmer
- [ ] Apply a correction curve on the duration of the shades of grey

### Very interesting alternative 
+ https://www.youtube.com/watch?v=MKzixF0ZObs
